language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.2
  - android-29
  - extra-android-m2repository
  - extra-google-m2repository
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.10.2.4988404"
  - echo y | sdkmanager "lldb;3.1"
    #  - sdkmanager --update
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

script:
  - "./gradlew assembleDebug"